name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.
publish_to: none

dependencies:
  audioplayers:
    git: https://github.com/kumsumit/audioplayers.git
  collection: ^1.18.0
  file_picker:
    git: https://github.com/sumitsharansatsangi/flutter_file_picker.git
  flutter:
    sdk: flutter
  http: ^1.3.0
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  provider: ^6.1.2

dev_dependencies:
  # Integration tests for audioplayers_platform_interface are handled
  # in this package to avoid maintaining multiple example apps:
  audioplayers_platform_interface:
    git: https://github.com/kumsumit/audioplayers_platform_interface.git
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0"
