name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 6.4.0
publish_to: none
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android:
    git: https://github.com/kumsumit/audioplayers_android.git
  audioplayers_darwin:
    git: https://github.com/kumsumit/audioplayers_darwin.git
  audioplayers_linux: 
    git: https://github.com/kumsumit/audioplayers_linux.git
  audioplayers_platform_interface:
    git: https://github.com/kumsumit/audioplayers_platform_interface.git
  audioplayers_web:
    git: https://github.com/kumsumit/audioplayers_web.git
  audioplayers_windows:
    git: https://github.com/kumsumit/audioplayers_windows.git
  file: '>=6.1.0 <8.0.0'
  flutter:
    sdk: flutter
  http: '>=0.13.1 <2.0.0'
  meta: ^1.9.1
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  synchronized: ^3.0.0
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

