name: audioplayers_test_server
publish_to: none

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  async: ^2.11.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  flutter_lints: ^6.0.0
  http: '>=1.4.0 <2.0.0'
